# Generated by Django 5.2.1 on 2025-05-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
        migrations.AlterModelTable(
            name='card',
            table='card',
        ),
        migrations.AlterModelTable(
            name='column',
            table='board_column',
        ),
    ]
